version: '3.8'
services:
  laravel-api:
    image: php:8.1-apache
    container_name: laravel-api
    working_dir: /var/www/html
    volumes:
      - ./sprint5-with-bugs:/var/www/html
    ports:
      - "8091:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    command: >
      bash -c "apt-get update &&
               apt-get install -y libpq-dev &&
               docker-php-ext-install pdo pdo_mysql &&
               composer install &&
               php artisan migrate &&
               php artisan db:seed &&
               apache2-foreground"
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toolshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: